# Path: ~/.streamlit/config.toml

[theme]
base="light"
primaryColor="#d33682"
backgroundColor="#fafafa"
secondaryBackgroundColor="#e0e0e0"
textColor="#262730"
font="sans serif"

[server]
enableCORS = false
headless = true
port = 8501
enableXsrfProtection = false
